baseurl = "/oceansandclimate/"
title = "Oceans and Climate"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author = "Oceans and Climate"
    description = "Science, Communication and Leadership at SEA Semester"
    keywords = "blog,developer,personal"
    info = "Science, Communication and Leadership at [SEA Semester](https://www.sea.edu)"
    avatarurl = ""
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/sea.css","css/custom.css","css/hero.css"]
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"


[[menu.main]]
  name = "About"
  weight = 1
  url = "/about/"
        
[[menu.main]]
  name = "Research"
  weight = 2
  url = "/s285_research/"
  
[[menu.main]]
  name = "Communication"
  weight = 3
  url = "/comms/"
